spring:
  application:
    name: mail-server
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-resolved-exception: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true